import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Lesson from "@/components/Lesson";
import { Navbar } from "@/components/Navbar";
import { Pricing } from "@/components/Pricing";
import { Testimonials } from "@/components/Testimonials";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[2000px] mx-auto overflow-hidden">
        <Navbar />
        <Hero />
        <Lesson />
        <Pricing />
        <Testimonials />
        <Footer />
      </main>
    </>
  );
}
